apiVersion: v1
kind: Pod
metadata:
  name: dev-nginx-pod
  namespace: dev-environment
spec:
  containers:
    - name: dev-nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80
