apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  namespace: nginx
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: example-job-pod
      labels:
        app: batch-job
    spec:
      containers:
        - name: hello
          image: busybox
          command: ["echo", "Hello, from k8s Job!"]
      restartPolicy: Never

