apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce # or ReadOnlyMany, ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/c/Kubernetes/nginx/volumes/PV"
