apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage-nginx-dep
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: stage-nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
