apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: apache
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: gpu
              operator: In
              values:
                - "true"
  containers:
    - name: apache
      image: httpd:latest
      imagePullPolicy: IfNotPresent
