# Role: Grants permissions within the "apache" namespace
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
- apiGroups: ["", "apps", "rbac.authorization.k8s.io", "batch"]
  resources: ["pods", "services", "deployments", "roles", "rolebindings", "jobs"]
  verbs: ["get", "apply", "create", "run", "patch", "list", "delete", "watch"]

