apiVersion: v1
kind: Pod
metadata:
  name: ssd-pod
  namespace: apache
spec:
  containers:
    - name: apache
      image: httpd:latest
      imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: ssd
                operator: In
                values:
                  - "true"
